import React from "react";
import Head from "next/head";
import styles from "../../styles/Products/Anacom.module.css";
import Image from "next/legacy/image";

export default function Anacom() {
  return (
    <>
      <Head>
        <title>Anacom | Digisat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.anacom}>
        <div className={styles.anacomHead}>
          <h2>Anacom</h2>
        </div>
        <div className={styles.anacomContent}>
          <div className={styles.aboutAnacom}>
            <div className={styles.anacomImg}>
              <Image
                src="/anacom1.jpg"
                layout="fill"
                objectFit="contain"
                alt="anacom"
              />
            </div>
            <h3>AnaSat® Transceivers</h3>
            <ul>
              <li>
                AnaCom's Outdoor and Indoor Satellite Microwave Equipment have
                an unmatched reputation for reliability.
              </li>
              <li>
                Our Monitor and Control capabilities allow customers
                unparalleled control over their AnaCom equipment.
              </li>
              <li>
                Most products work easily with our Redundancy Protection Switch
                systems for true plug-and-play protection.
              </li>
            </ul>
          </div>
          <table>
            <tbody>
            <tr>
              <th>Band</th>
              <th>Transmit Frequency</th>
              <th>Receive Frequency</th>
            </tr>
            <tr>
              <td>Extended C-Band</td>
              <td>5.850 - 6.425 GHz</td>
              <td>3.625 - 4.200 GHz</td>
            </tr>
            <tr>
              <td>Super Extended C-Band</td>
              <td>5.850 - 6.725 GHz</td>
              <td>3.400 - 4.200 GHz</td>
            </tr>
            <tr>
              <td>INSAT C-Band</td>
              <td>6.725 - 7.025 GHz</td>
              <td>4.500 - 4.800 GHz</td>
            </tr>
            <tr>
              <td>Palapa C-Band</td>
              <td>6.425 - 6.725 GHz</td>
              <td>3.400 - 3.700 GHz</td>
            </tr>
            <tr>
              <td>Russian C-Band</td>
              <td>5.975 - 6.475 GHz</td>
              <td>3.650 - 4.150 GHz</td>
            </tr>
            <tr>
              <td>LMI C-Band</td>
              <td>5.725 - 6.025 GHz</td>
              <td>3.700 - 4.000 GHz</td>
            </tr>
            <tr>
              <td>Standard Ku-Band</td>
              <td>14.0 - 14.5 GHz</td>
              <td>10.95 - 12.75 GHz</td>
            </tr>
            <tr>
              <td>Extended Ku-Band</td>
              <td>13.75 - 14.25 GHz</td>
              <td>10.95 - 12.75 GHz</td>
            </tr>
            <tr>
              <td>Super Extended Ku</td>
              <td>13.75 - 14.50 GHz</td>
              <td>10.95 - 12.75 GHz</td>
            </tr>
            </tbody>
          </table> 
        </div>
      </div>
    </>
  );
}
