import React from 'react'
import Head from "next/head"
import styles from "../../styles/Products/AntennaControl.module.css"
import Image from "next/legacy/image"

export default function AntennaControl() {
  return (
    <>
      <Head>
    <title>Antenna Control System | Digisat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>  
    <div className={styles.antennaControl}>
<div className={styles.antennaControlHead}>
<h2>Antenna Control System</h2>
</div>
<div className={styles.antennaControlContent}>
<div className={styles.aboutAtx}>
<div className={styles.atxImg}>
<Image src="/antenna _control_system.png" objectFit='contain' layout='fill' alt='atx'/>
</div>
<h3>Antenna Control System</h3>
<div className={styles.modelName}>Model No. ATX 3000</div>
</div>
<div className={styles.section}>
<h4>Atx Features</h4>
<ul>
    <li><h5>Multiple Peaking and history track algorithm set:</h5>
    <p>Multiple user selectable peaking / history track algorithms. SSC has introduced our best peaking algorithm ever! With our newest peaking algorithm the ATX 3000 delivers maximum performance with minimal signal loss.</p></li>
    <li><h5>Foul weather feature - FWx:</h5>
    <p>Don’t let rain fade and controller performance ruin your link! Our latest foul weather feature allows a user to either locally or remotely select our new FWx - foul weather feature mode. When bad weather is approaching or has arrived, the user can select our new foul weather mode feature. With our new proprietary FWx mode the tracker delivers maximum performance and signal during bad weather. The user can select the duration of the FWx based on the weather conditions.
</p></li>
    <li><h5>Remote operation from anywhere in the world!:</h5>
    <p>Satellite system introduces full remote control for your antenna controller. Now with our latest Monitor and Control software we have added full antenna control. Great for remote operation of multiple antennas or correct antenna position instantly without having to travel to the site whether it is 1 mile away or 10,000 miles away!</p></li>
    <li><h5>AC and DC solutions:</h5>
    <p>Multiple AC and DC solutions available, please contact factory for your application. Satellite Systems announces the new control GUI Version 2.0 for our antenna control product line. Enhanced control features allow for remote control of your antenna and additional monitoring tools are included such as strip charting for signal strength, Azimuth & Elevation movement. Version 2.0 also includes a new event-triggered alarm feature that allows for email notification to your laptop / cell phone or PDA. Alarms are triggered via signal strength, loss of signal, and other conditions. New logging to file feature allows for analysis of controller events. Easily imported to Excel. Revolving log file saving feature automatically closes the file and starts a new file once per day for archiving and date stamping purposes.</p></li>
</ul>
</div>
<div className={styles.section}>
    <h4>Positioning Methods</h4>
    <ul>
        <li><h5>Designate</h5><p>Automatically moves the antenna in each axis to one of 99 pre-stored satellite positions.</p></li>
        <li><h5>Direct Az / El:</h5>
        <p>Automatically moves the antenna in each axis to the coordinates entered via the front panel.</p></li>
        <li><h5>Jog</h5><p>Manually moves the antenna in each axis in response to front panel controls.</p></li>
        <li><h5>Peak</h5><p>Performs a peaking algorithm on the current target.</p></li>
        <li><h5>Step Track</h5><p>Automatically performs peaking algorithm in response to input signal level decreasing below a programmable minimum.</p></li>
        <li><h5>History Track</h5><p>Automatically moves the antenna in each axis along a sidereal time tagged path. (History track is often referred to as Memory Track or Program Track).</p></li>
        <li><h5>External</h5><p>Moves the antenna in each axis in response to commands received through the active monitor and control port.</p></li>
    </ul>
</div>
<div className={styles.section}>
<h4>Performance</h4>
<ul>
    <li><h5>Accuracy</h5><p>Antenna pointing accuracy within ten percent of the 3dB Beamwidth. Tracking Resolution: &gt; 0.05 degrees with Properly specified position Sensor.</p></li>
</ul>
</div>
<div className={styles.section}>
<h4>Interfaces</h4>
<ul>
    <li><h5>Reference</h5><p>Accepts input of linear, analog signal reference from 0 - 20 VDC. Internal op amp circuit provides pre-scaling of gain and slope of tracking reference signal. Final scaling is provided through software.</p></li>
    <li><h5>M&amp;C</h5><p>Accepts RS-232 / RS-485 (4-wire) data / Ethernet via RJ45 10/100 Base T for remote monitor and control of all controller functions. ATX monitor / control software suite is included.</p></li>
    <li><h5>Front Panel</h5><p>Large Graphic VFD displays antenna position, signal level and operating mode. Keypad provided for user inputs.</p></li>
    <li><h5>Motor Control</h5><p>The rack mounted microprocessor controller is linked to any of motor control options by serial interface cable.</p></li>
    <li><h5>Prime Power (ACU)</h5><p>90 - 260 VAC, 47 - 63 Hz, single-phase, auto sensing, 65 watts maximum.</p></li>
</ul>
</div>
<div className={styles.section}>
<h4>Monitor and Control Software for ATX 3000 Antenna Controller</h4>
<ul>
    <li><h5>Event triggered alarms</h5><p>Any alarm conditions can be sent to the user via email to your laptop / cell phone or PDA. Events can be triggered via signal strength, AZ, EL, & POL movements, communication errors and other threshold parameters.</p></li>
<li><p>Any alarm conditions can be sent to the user via email to your laptop / cell phone or PDA. Events can be triggered via signal strength, AZ, EL, & POL movements, communication errors and other threshold parameters.</p></li>
<li><p>Large easy to read signal strength panel.</p></li>
<li><p>Event triggered alarms / Easy to use email control. Email multiple users / multiple alarm parameters.</p></li>
<li><h5>Status monitor</h5><p>The status monitor panel allows for real time data of your systems status.</p></li>
<li><h5>Strip Chart utility</h5><p>Strip charting utility allows for recording of signal strength and AZ&EL motor movements. Events are recorded and presented on time based event chart. Additional logging feature allows for tab delimited file that can be imported into your favorite spreadsheet program. The log files can be automatically saved and restarted on a daily basis and pulled up later for review of tracking performance.</p></li>
<li><p>Revolving log file saving feature allows user to automatically back up log files for later analysis of controller events. Easily imported to Excel or other spread sheet programs.</p></li>
</ul>
</div>
<div className={styles.section}>
<h4>Antenna Drive Units for AC Motors</h4>
<ul>
    <li><p>Solid-state variable frequency 3 phases AC motor controllers with microprocessor motor speed management.</p></li>
    <li><p>Static braking with torque at 150% of rated motor torque.</p></li>
    <li><p>Variable speed control 0 to 60 Hz with constant torque</p></li>
    <li><p>Low frequency voltage boost 150% starting torque under 20% speed.</p></li>
    <li><p>Local jog control and Emergency Stop switch are provided at the ADU.</p></li>
    <li><p>Optional handheld remote jog control is available.
HP configuration options: 1 - 10 hp available.
</p></li>
</ul>
</div>
<div className={styles.section}>
<h4>AC System Standard Dimensions</h4>
<ul>
    <li><p><b>ACU</b>: 1 RU, 19" x 15.5" x 1.75".</p></li>
    <li><p><b>ADU</b>: Dual axis 3 phase AC motor control unit is a NEMA-4 outdoor enclosure 16"W x 20"H x 9"D. Some configurations may require a larger enclosure.
</p></li>
</ul>
</div>
<div className={styles.section}>
<h4>DC System Standard Dimensions</h4>
<ul>
    <li><p><b>ACU</b>: 1 RU, 19" x 15.5" x 1.75".</p></li>
    <li><p><b>ADU</b>: 1 RU, 19" x 15.5" x 1.75" (Enclosure solution also available).
</p></li>
</ul>
</div>
<div className={styles.section}>
<h4>Interconnections</h4>
<ul>
<li><p>Local AC main power is required at the ADU.</p></li>
<li><p>A two conductor, 20 gauge shielded cable from the ADU to indoor ACU interface is required.</p></li>
<li><p>Required Limit switches connect to ADU.</p></li>
<li><p>Extra Emergency stop switches may connect to ADU.</p></li>
<li><p>High resolution absolute, brushless resolvers or optical position encoders mount directly on antenna Az and El pivot axis.</p></li>
</ul>
</div>
<div className={styles.section}>
<h4>Antenna Drive Units for DC Motors</h4>
<p>DC Motor jacks provided by SSC in 12 - 48 inch stroke lengths. Built in encoder feedback. 24 / 36 VDC / integrated limit switches. (DC systems jacks are quoted separately).</p>
</div>
<div className={styles.section}>
<h4>Options</h4>
<p>Motors, Gear reducers, Jack screws, Limit switches, Emergency stop switches, umbilical control.
</p>
</div>
</div>
    </div>
    </>
  )
}
