import React from 'react'
import Head from "next/head"
import styles from "../../styles/Products/ATX.module.css"

export default function Atx() {
  return (
    <>
      <Head>
      <title>ATX | Digisat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.atx}>
        <div className={styles.atxHead}>
<h2>Satellite Systems Corporation Model ATX-3000</h2>
        </div>
        <div className={styles.atxContent}>
<h3>Built-in features includes</h3>
<div className={styles.features}>
<h4>Antenna Tracking Controller</h4>
<ul>
    <li>The ATX-3000 antenna tracking controller is a user-friendly microprocessor-based system to reliably track inclined orbit satellites</li>
    <li>Fully programmable positioner with memories for up to 99 satellites.</li>
    <li>Automatic Calibration for true Azimuth and Elevation displayed in 0.01 degrees.</li>
    <li>High resolution Brushless resolvers for ultimate position feedback.</li>
</ul>
</div>
<div className={styles.features}>
<h4>Positioning Methods</h4>
<ul>
    <li><b>Designate:</b> Automatically moves the antenna in each axis to one of 99 pre-stored satellite positions.</li>
    <li><b>Direct Az/El:</b> Automatically moves the antenna in each axis to the coordinates entered via the front panel.</li>
    <li><b>Jog:</b> Manually moves the antenna in each axis in response to front panel controls.</li>
    <li><b>Peak:</b> Performs a peaking algorithm on the current target.</li>
    <li><b>Step Track:</b> Automatically performs peaking algorithm in response to input signal level decreasing below a programmable minimum.</li>
    <li><b>Program Track:</b>Automatically moves the antenna in each axis along a sidereal time tagged path.</li>
    <li><b>External:</b> Moves the antenna in each axis in response to commands received through the serial port.</li>
</ul>
</div>
<div className={styles.features}>
<h4>Performance</h4>
<ul>
    <li><b>Reference:</b>Antenna pointing accuracy within ten percent of the 3dB beamwidth.</li>
    <li><b>Tracking Resolution:</b> &gt;0.05 degrees with properly specified position sensor.</li>
</ul>
</div>
<div className={styles.features}>
<h4>Interfaces</h4>
<ul>
    <li><b>Reference:</b> Accepts input of linear, analog signal reference from 0 - 20 VDC. Internal op amp circuit provides pre-scaling of gain and slope of tracking reference signal. Final scaling is provided through software.</li>
    <li><b>Serial Data:</b> Accepts RS-232 or RS-485 (4-wire) data for remote monitor and control of all controller functions.</li>
    <li><b>Front Panel:</b> Large Graphic VFD displays antenna position, signal level and operating mode. Keypad provided for user inputs.
</li>
    <li><b>Motor Control:</b> The rack mounted microprocessor controller is linked to any of SSC's motor control options by serial interface cable.</li>
    <li><b>Prime Power (ACU):</b> 90 - 260 VAC, 47 - 63 Hz, single-phase, auto sensing, 65 watts maximum.
</li>
</ul>
</div>
<div className={styles.features}>
    <h4>Antenna Drive Units for AC Motors</h4>
<ul>
    <li>Solid-state variable frequencies 3 phase AC motor controllers with microprocessor motor speed management.</li>
    <li>Static braking with torque at 150% of rated motor torque.</li>
    <li>Variable speed control 0 to 60 Hz with constant torque.</li>
    <li>Low frequency voltage boost 150% starting torque under 20% speed.</li>
    <li>Local jog control and Emergency Stop switch are provided at the ADU.</li>
    <li>Optional handheld remote jog control is available.</li>
    <li>Two voltage configuration options: (must be specified at time of order.) 220 - 240 Volts, 47 - 63 Hz single- or three-phase prime power, 220 - 240 Volts three-phase motors.
– OR –
380 - 460 Volts, 47 - 63 Hz single- or three-phase prime power, 380 - 460 Volts three-phase motors.
(A single-phase 90 - 260 VAC, 47 - 63 Hz, 45 watts maximum is also require for outdoor controls).</li>
    <li>HP configuration options: 1 - 5 hp available.</li>
</ul>
</div>
<div className={styles.features}>
    <h4>Options</h4>
    <ul>
        <li>Motors, Gear reducers, Jack screws, Limit switches, Emergency stop switches.</li>
    </ul>
</div>
<div className={styles.features}>
<h4>Beacon Receivers</h4>
<ul>
<li>Designed to work in concert with SSC Model 3434 line of Beacon Tracking Receivers.</li>
</ul>
</div>
        </div>
      </div>
    </>
  )
}
