import React from 'react'
import styles from "../../styles/Products/CCOM.module.css"
import Head from "next/head"
import Image from "next/legacy/image"

export default function CCOM() {
  return (
    <>
      <Head>
      <title>C-COM | Digisat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.ccom}>
        <div className={styles.ccomHead}>
<h2>C-COM</h2>
        </div>
        <div className={styles.ccomContent}>
<div className={styles.ccomProducts}>
<div className={styles.ccomImg}>
<Image src="/Ka-75V.jpg" layout='fill' objectFit='contain' alt='Ka-75V'/>
</div>
<h3>Features</h3>
<ul>
  <li>One-Piece, high surface accuracy, offset feed, steel reflector</li>
  <li>Designed to work with the iNetVu® 7024C Controller</li>
  <li>Works seamlessly with the world’s emerging commercial ViaSat/KA-SAT satellite Surfbeam Works seamlessly with the world’s emerging commercial ViaSat/KA-SAT satellite Surfbeam</li>
  <li>Auto beam select on KA-SAT Tooway services</li>
  <li>PRO Auto-acquire modems</li>
  <li>One button, auto-pointing controller acquires Ka-band satellite within 2 minutes</li>
  <li>Locates satellites using the most advanced satellite acquisition methods</li>
</ul>
</div>
<div className={styles.ccomProducts}>
<div className={styles.ccomImg}>
<Image src="/Ka-75-KAVAT.jpg" layout='fill' objectFit='contain' alt='Ka-75V-KAVAT'/>
</div>
<h3>Features</h3>
<ul>
  <li>One-Piece, high surface accuracy, offset feed, steel reflector</li>
  <li>Heavy duty feed arm now supports both type of Transceivers: Standard Tria and new eTRIA</li>
  <li>Designed to work with the iNetVu® 7024C Controller</li>
  <li>Auto beam select on KA-SAT Tooway services</li>
  <li>Supports manual control when required</li>
  <li>One button, auto-pointing controller acquires any Ka-band satellite within 2 minutes</li>
  <li>Field upgradable to Ku-band</li>
  <li>Locates satellites using the most advanced satellite acquisition methods</li>
  <li>Supports Skyware Global 98 cm Ka antenna and 3W transceiver</li>
  <li>Avanti approved; also compliant with Gilat (SkyEdge) Ka services</li>
  <li>Available with pod option</li>
  <li>Standard 2 year warranty</li>
</ul>
</div>
<div className={styles.ccomProducts}>
<div className={styles.ccomImg}>
<Image src="/Ka-98G.jpg" layout='fill' objectFit='contain' alt='Ka-98G.jpg'/>
</div>
<h3>Features</h3>
<ul>
  <li>One-Piece, high surface accuracy, offset feed, steel reflector</li>
  <li>Heavy duty feed arm capable of supporting up to 5kg (10 lbs) RF transceiver</li>
  <li>Designed to work with the iNetVu® 7024C Controller</li>
  <li>Works seamlessly with the world’s most popular commercially available Ka modems and services</li>
  <li>2 Axis motorization (3 Axis Optional)</li>
  <li>Supports manual control when required</li>
  <li>One button, auto-pointing controller acquires Ka-band satellite within 2 minutes</li>
  <li>Locates satellites using the most advanced satellite acquisition methods</li>
  <li>Based on Skyware Global 98 cm reflector with cross-pol feed</li>
  <li>Uses long focal length feed for low cross-pol performance</li>
  <li>Available with pod option</li>
  <li>Standard 2 year warranty</li>
</ul>
</div>
<div className={styles.ccomProducts}>
<div className={styles.ccomImg}>
<Image src="/Ka-98G.jpg" layout='fill' objectFit='contain' alt='Ka-98G.jpg'/>
</div>
<h3>Features</h3>
<ul>
  <li>One-Piece, high surface accuracy, offset feed, steel reflector</li>
  <li>Heavy duty feed arm capable of supporting up to 13.5kg (30 lbs) RF Electronics (LNB & BUC)</li>
  <li>Designed to work with the iNetVu® 7024C Controller</li>
  <li>Works seamlessly with the world’s most popular commercially available Ku modems and services</li>
  <li>3 Axis motorization</li>
  <li>Field upgradable to Ka-band</li>
  <li>One button, auto-pointing controller acquires Ka-band satellite within 2 minutes</li>
  <li>Locates satellites using the most advanced satellite acquisition methods</li>
  <li>Based on Skyware Global 98 cm reflector with cross-pol feed</li>
  <li>Uses long focal length feed for low cross-pol performance</li>
  <li>Available with pod option</li>
  <li>Standard 2 year warranty</li>
</ul>
</div>
        </div>
    </div>
    </>
  )
}
