import Head from 'next/head'
import React from 'react'
import styles from "../../styles/Products/Convertors.module.css"
import Image from 'next/legacy/image'

export default function Convertors() {
  return (
    <>
    <Head>
    <title>Converters | Digisat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>  
    <div className={styles.convertors}>
<div className={styles.convertorsHead}>
<h2>Convertors</h2>
</div>
<div className={styles.convertorsContent}>
<div className={styles.aboutConvertors}>
<div className={styles.convertorImg}>
<Image src="/converter_up.gif" alt='convertor' layout='fill' objectFit='contain'/>
</div>
<h3>Convertor</h3>
</div>
<div className={styles.modelChart}>
<h4>Frequency Convertor Model Chart</h4>
<h5>Down Convertors</h5>
<div>
<div className={styles.models}>
    <div className={styles.model}>
      <h6>
      Series 4003 LNBs Model 4100
      </h6>
      <div className={styles.details}>
<div className={styles.detail}>
Input Frequency
</div>
<div className={styles.detail}>
10.7 - 12.75 GHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Output Frequency
</div>
<div className={styles.detail}>
950 - 2000 MHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Tuning
</div>
<div className={styles.detail}>
Band split into two sub-bands
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Spectral
</div>
<div className={styles.detail}>
Non-inverting
</div>
      </div>
    </div>
    <div className={styles.model}>
      <h6>
      Series 4003 LNBs Model 4421
      </h6>
      <div className={styles.details}>
<div className={styles.detail}>
Input Frequency
</div>
<div className={styles.detail}>
950 - 1450 MHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Output Frequency
</div>
<div className={styles.detail}>
52 - 88 MHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Tuning
</div>
<div className={styles.detail}>
Transponders 1-24
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Spectral
</div>
<div className={styles.detail}>
Inverting NOTE: M&C availability is RS-232 ONLY
</div>
      </div>
    </div>
    <div className={styles.model}>
      <h6>
      Series 4003 LNBs Model 4500
      </h6>
      <div className={styles.details}>
<div className={styles.detail}>
Input Frequency
</div>
<div className={styles.detail}>
950 - 1525 MHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Output Frequency
</div>
<div className={styles.detail}>
52 - 88 MHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Tuning
</div>
<div className={styles.detail}>
1 MHz steps
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Spectral
</div>
<div className={styles.detail}>
Inverting, or Non-inverting, Front panel selectable
</div>
      </div>
    </div>
    <div className={styles.model}>
      <h6>
      Series 4003 LNBs Model 4510
      </h6>
      <div className={styles.details}>
<div className={styles.detail}>
Input Frequency
</div>
<div className={styles.detail}>
950 to 1500 MHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Output Frequency
</div>
<div className={styles.detail}>
61 to 79 MHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Tuning
</div>
<div className={styles.detail}> - </div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Spectral
</div>
<div className={styles.detail}>
Ku-band (non-inverted)
</div>
      </div>
    </div>
    </div>
    <div className={styles.models}>
    <div className={styles.model}>
      <h6>
      Series 4027 BDCs Model 4800-CL
      </h6>
      <div className={styles.details}>
<div className={styles.detail}>
Input Frequency
</div>
<div className={styles.detail}>
3.4 - 4.2 GHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Output Frequency
</div>
<div className={styles.detail}>
950 - 1750 MHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Spectral
</div>
<div className={styles.detail}>
Inverted
</div>
      </div>
    </div>
    <div className={styles.model}>
      <h6>
      Series 4027 BDCs Model 4800 XL
      </h6>
      <div className={styles.details}>
<div className={styles.detail}>
Input Frequency
</div>
<div className={styles.detail}>
7.25 - 7.75 GHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Output Frequency
</div>
<div className={styles.detail}>
950-1450 MHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Spectral
</div>
<div className={styles.detail}>
Non-Inverted
</div>
      </div>
    </div>
    <div className={styles.model}>
      <h6>
      Series 4027 BDCs Model 4800 Kel
      </h6>
      <div className={styles.details}>
<div className={styles.detail}>
Input Frequency
</div>
<div className={styles.detail}>
11.7 - 12.75 GHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Output Frequency
</div>
<div className={styles.detail}>
950-2000 MHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Spectral
</div>
<div className={styles.detail}>
Non-Inverted
</div>
      </div>
    </div>
    </div>
</div>
<h5>Up Convertors</h5>
<div className={styles.models}>
    <div className={styles.model}>
      <h6>
      Series 4027 BDCs Model 5410
      </h6>
      <div className={styles.details}>
<div className={styles.detail}>
Input Frequency
</div>
<div className={styles.detail}>
52 to 88 MHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Output Frequency
</div>
<div className={styles.detail}>
950 - 1525 MHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Tuning
</div>
<div className={styles.detail}> - </div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Spectral
</div>
<div className={styles.detail}> - </div>
      </div>
    </div>
    <div className={styles.model}>
      <h6>
      Series 4027 BDCs Model 5420
      </h6>
      <div className={styles.details}>
<div className={styles.detail}>
Input Frequency
</div>
<div className={styles.detail}>
52 - 88 MHz	
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Output Frequency
</div>
<div className={styles.detail}>
950 - 1450 MHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Tuning
</div>
<div className={styles.detail}>
1 MHz steps
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Spectral
</div>
<div className={styles.detail}>
Non-inverting
</div>
      </div>
    </div>
    <div className={styles.model}>
      <h6>
      Series 4027 BDCs Model 5425
      </h6>
      <div className={styles.details}>
<div className={styles.detail}>
Input Frequency
</div>
<div className={styles.detail}>
52 - 88 MHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Output Frequency
</div>
<div className={styles.detail}>
950 - 1450 MHz
</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Tuning
</div>
<div className={styles.detail}>1 MHz steps</div>
      </div>
      <div className={styles.details}>
<div className={styles.detail}>
Spectral
</div>
<div className={styles.detail}>
Non-inverting NOTE: This model includes 24VDC @ 60 watts and 10 MHz reference multiplexed on output port for direct driving of outdoor BUC transmit heads.
</div>
      </div>
    </div>
    </div>
</div>
</div>
    </div>
    </>
  )
}
