import React from 'react'
import Head from 'next/head'
import Image from "next/legacy/image"
import styles from "../../styles/Products/DCSS.module.css"
export default function DCSS() {
  return (
    <>
<Head>
    <title>DCSS | Digisat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>  
    <div className={styles.dcss}>
       <div className={styles.dcssHead}>
<h2>DCSS Technology</h2>
       </div>
       <div className={styles.dcssContent}>
        <div className={styles.aboutDcss}>
<div className={styles.dcssImg}>
<Image src="/dcss.png" layout='fill' objectFit='contain' alt='dcss'/>
</div>
<h3>DCSS Technology</h3>
</div>
<div className={styles.features}>
<p>CSS stands for Channel Stacking Switch. It is technology of converting multiple transponders to any output frequency.</p>
<p>DCSS stands for Digital Channel Stacking Switch.</p>
<p>CSS technology has been created by means of analogue integrated circuits. Latest progress of DSP (Digital Signal Processing) technology allowed to move the CSS technology in digital domain. The frequency conversion, amplification, filtering, etc. is now performed by powerful DSP processors and software algorithms.</p>
<p>SCR is technology that enables delivery of satellite transponders to multiple users (receivers) over a single coax cable. SCR technology uses DCSS LNB as device producing stacked transponders on single coax cable. Receivers must have the software adopted for SCR technology.</p>
<p>DCSS multiswitch stands for digital Channel Stacking Switch. DCSS multiswitch performing channel stacking in digital domain. It is equipped in powerful DSP processor by MaxLinear. It can generate up to 24 conversions to SAT-IF-Band. It can work in dynamic as well as static mode. All the User Band parameters are programmable.</p>
</div>
       </div>
    </div>      
    </>
  )
}
