import React from "react";
import Head from "next/head";
import Image from "next/legacy/image";
import styles from "../../styles/Products/Norsat.module.css";
export default function Norsat() {
  return (
    <>
      <Head>
        <title>Norsat | Digisat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.norsat}>
        <div className={styles.norsatHead}>
          <h2>Norsat</h2>
        </div>
        <div className={styles.norsatContent}>
          <div className={styles.aboutNorsat}>
            <div className={styles.norsatImg}>
              <Image
                src="/norsat1.jpg"
                layout="fill"
                objectFit="contain"
                alt="norsat"
              />
            </div>
            <h3>Norsat&#39;s Low Noise Blocks</h3>
            <p>
              Norsat&#39;s Low Noise Blocks (LNBs) provide signal reception for
              satellite communications around the world. We offer premium
              performance and reliability in the smallest form factor possible.
              All of the standard Ku-Band LNBs are backed by a 3 year warranty
              and nearly forty years of experience as the industry&#39;s leading
              provider of high performance LNBs.
            </p>
          </div>
          <div className={styles.features}>
            <div className={styles.lnb}>
              <h4>Norsat LNBs feature</h4>
              <ul>
                <li>
                  The industry&#39;s best LO (Local Oscillator) stability.
                </li>
                <li>High performance for any application.</li>
                <li>Excellent availability and short lead times.</li>
              </ul>
            </div>
          </div>
          <div className={styles.bdc}>
            <h4>BDC</h4>
            <p>
              Norsat&#39;s Block Downconverters (BDCs) provide high performance
              signal conversion for satellite communication. Norsat BDCs
              feature:
            </p>
          </div>
          <div className={styles.bdcFeatures}>
            <h4>Norsat BDC feature</h4>
            <ul>
              <li>Compatibility with all Norsat LNAs</li>
              <li>Highest quality performance</li>
              <li>
                Compatibility with large satellite systems and earth stations
              </li>
              <li>Cost effective tool to replace rack mounted BDCs</li>
            </ul>
          </div>
          <div className={styles.bucs}>
            <h4>BLOCK UPCONVERTER (BUCS): KU-BAND</h4>
            <p>
              Norsat&#39;s Block Upconverter&#39;s (BUCs) provide signal
              transmission for satellite communications around the world. We
              offer premium performance and reliability in the smallest form
              factor possible. All of our standard BUCs are backed by a 2 year
              warranty and nearly forty years of experience as the
              industry&#39;s leading provider of high performance BUCs.
            </p>
          </div>
          <div className={styles.bucsFeatures}>
            <h4>Norsat BUCS features</h4>
            <ul>
              <li>High performance for any application</li>
              <li>Excellent availability and short lead times</li>
            </ul>
          </div>
          <div className={styles.norsatModels}>
              <div className={styles.model}>
                <h5>BDC-1000 Ku PLL</h5>
                <div className={styles.details}>
                  <div className={styles.detail}>
                    <div>Input Freq.(GHz)</div>
                    <div>10.7–12.75</div>
                  </div>
                  <div className={styles.detail}>
                    <div>LO Freq.(GHz)</div>
                    <div>9.75–11.30</div>
                  </div>
                  <div className={styles.detail}>
                    <div>Noise Fig/Temp. (dB)</div>
                    <div>15</div>
                  </div>
                  <div className={styles.detail}>
                    <div>LO Stabilities Avail.</div>
                    <div>±30 kHz</div>
                  </div>
                </div>
              </div>
              <div className={styles.model}>
                <h5>BDC-1000X Ku Ext Ref</h5>
                <div className={styles.details}>
                  <div className={styles.detail}>
                    <div>Input Freq.(GHz)</div>
                    <div>10.7–12.75</div>
                  </div>
                  <div className={styles.detail}>
                    <div>LO Freq.(GHz)</div>
                    <div>9.75–11.30</div>
                  </div>
                  <div className={styles.detail}>
                    <div>Noise Fig/Temp. (dB)</div>
                    <div>15</div>
                  </div>
                  <div className={styles.detail}>
                    <div>LO Stabilities Avail.</div>
                    <div>Phase Locked to 10 Mhz</div>
                  </div>
                </div>
              </div>
              <div className={styles.model}>
                <h5>BDC-1000X AIRBORNE</h5>
                <div className={styles.details}>
                  <div className={styles.detail}>
                    <div>Input Freq.(GHz)</div>
                    <div>10.7–12.75</div>
                  </div>
                  <div className={styles.detail}>
                    <div>LO Freq.(GHz)</div>
                    <div>9.75–10.60</div>
                  </div>
                  <div className={styles.detail}>
                    <div>Noise Fig/Temp. (dB)</div>
                    <div>0.8</div>
                  </div>
                  <div className={styles.detail}>
                    <div>LO Stabilities Avail.</div>
                    <div>Phase Locked to 10 Mhz</div>
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
    </>
  );
}
