import React from 'react'
import Head from "next/head"
import styles from "../../styles/Products/Radeus.module.css"
import Image from "next/legacy/image"

export default function Radeus() {
  return (
    <>
    <Head>
    <title>Radeus | Digisat</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <div className={styles.radeus}>
        <div className={styles.radeusHead}>
<h2>Radeus</h2>
        </div>
        <div className={styles.radeusContent}>
<div className={styles.aboutRadeus}>
<div className={styles.radeusImg}>
<Image src="/radeus.jpg" objectFit='contain' layout='fill' alt="radeus"/>
</div>
<h3>Radeus Labs 8200 ACU</h3>
<p>Established in 2002 in Poway, California near San Diego, Radeus Labs is a leader in the design, manufacture and marketing of high performance computing and antenna control products to the commercial and military markets.</p>
</div>
<div className={styles.history}>
<h4>History</h4>
<ul>
    <li>2002 – Founding of Radeus Labs Inc., Poway, CA</li>
    <li>2014 – Radeus begins design of 8200/8250 ACS leveraging design team that developed the Vertex Communications 7200 ACU</li>
    <li>2015 – Company purchased by Ken Cone, CTO and Juliet Correnti, CEO</li>
    <li>2016 - Radeus releases 8200 legacy ACU designed to directly drop in for the Vertex Communications 7200 ACU</li>
    <li>2016 – Radeus releases the 8200/8250 high performance system for new installations/complete retrofits</li>
    <li>2017 - Radeus releases NORAD 2 line element and Intelsat 11 element tracking modes and develops -55C low temp specification for 8250 outdoor drive cabinet
</li>
</ul>
</div>
<div className={styles.features}>
<h4>Features</h4>
<ul>
    <li>4-rack unit chassis saves space</li>
    <li>Dedicated jog panel controls</li>
    <li>Efficient, intuitive graphical user interface</li>
    <li>Setup Wizard for limit and motor tuning</li>
    <li>SNMP M&C interface</li>
    <li>ingle (True) Ethernet IFL (with 8250)</li>
    <li>Remote operation through Team Viewer</li>
    <li>“In-service” software update capable</li>
    <li>Low power design with no cooling fan to draw in dust
</li>
</ul>
</div>
        </div>
    </div>
  </>
  )
}
