import React from 'react'
import styles from "../../styles/Products/Xicom.module.css"
import Image from "next/legacy/image"
import Head from 'next/head'

export default function Xicom() {
  return (
    <>
    <Head>
    <title>Xicom | Digisat</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </Head>
    <div className={styles.xicom}>
      <div className={styles.xicomHead}>
<h2>Xicom Technologies</h2>
      </div>
      <div className={styles.xicomProducts}>
<div className={styles.xicomProduct}>
<div className={styles.productImage}>
<Image src="/sspAmp.jpg" layout='fill' objectFit='contain' alt='Solid State Power Amplifiers'/>
</div>
<h3>Solid State Power Amplifiers</h3>
<p>Xicom Technology is delivering innovative SSPAs (Solid-State Power Amplifiers) designed to cover your SATCOM and Tropo requirements. We have integrated the compact, robust design with the reliability and long-term cost savings of a SSPA.</p>
</div>
<div className={styles.xicomProduct}>
<div className={styles.productImage}>
<Image src="/antenna-mounted.jpg" layout='fill' objectFit='contain' alt='Antenna-mounted TWTAs'/>
</div>
<h3>Antenna-mounted TWTAs</h3>
<p>Xicom&#39;s antenna-mounted TWTAs are known worldwide for their reliable operation and long life. By eliminating the need for long waveguide runs, transmit power is optimized and RF Losses are reduced. Acclaimed for their compact and highly efficient design, Xicom&#39;s antenna-mount amplifiers dramatically reduce both installation and operation costs.</p>
</div>
<div className={styles.xicomProduct}>
<div className={styles.productImage}>
<Image src="/comtech.png" layout='fill' objectFit='contain' alt='SoComtech HPA Content'/>
</div>
<h3>SoComtech HPA Content</h3>
<p>The XTD-400 is a compact self contained antenna mountable high power amplifier (HPA) designed for low cost installation and long life. The outdoor design eliminates the need for an amplifier shelter as well as a long waveguide run between the amplifier and the antenna feed horn. RF filters, cooling, and monitoring & control (M&C) systems are all self contained within the HPA.</p>
</div>
      </div>
    </div>
    </>
  )
}
