import React from "react";
import Head from "next/head";
import styles from "../styles/About.module.css";
import Image from "next/legacy/image";

export default function About() {
  return (
    <>
      <Head>
        <title>About | Digisat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.about}>
        <div className={styles.aboutHead}>
          <h2>About Digisat</h2>
        </div>
        <div className={styles.aboutContent}>
          <div className={styles.aboutUs}>
            <h3>About Us</h3>
            <div className={styles.Img}>
            <Image src="/digisat-company.jpg" objectFit="cover" layout="fill"/>
            </div>
            <p>
              Digisat is your single key experts and trusted Satcom products,
              solutions & services provider of Satellite Equipment, Satcom
              Systems and Turnkey Satellite Communication Solutions. We deliver
              high quality, reliable Satellite Solutions to all markets and
              worldwide for applications such as Mobile VSAT Satellite
              Communications, Gateway Earth Stations, Maritime VSAT, Satcom on
              the move, Flyaway VSAT, Satellite Teleports, Remote
              Communications, Disaster Communications, Internet Access and
              Telemetry. From Ku-Band Satcom Gateways to Mobile VSAT Terminals
              and Marine Satellite Communications, the Digisat team keeps you
              connected anywhere. As a value added authorized sales / services.
              Reply your total satellite solution needs. From a single satellite
              Earth Station Antenna / mobile antenna / modem / set top Box to
              turnkey services with support of Hughes services and DishTV
              services.You can count on Digisat as a single source for all of
              your procurement requirements.
            </p>
          </div>
          <div className={styles.history}>
            <h3>Our History</h3>
            <div className={styles.Img}>
            <Image src="/digisat.jpg" objectFit="cover" layout="fill"/>
            </div>
            <p>
              Evolving for over 20 years with the advancements in Satcom
              Technology, Digisat (formally DIGISAT). Provides industry leading
              satellite communications solutions, equipment, services and
              professional support personnel to global customers. As a rapidly
              growing, privately held, international communications corporation
              that delivers total communication solutions to the global
              community, our solutions encompass all aspects of satellite,
              wireless and terrestrial communications. From mobile Satcom to
              engineered turn-key flyaway VSAT terminals, maritime internet
              systems and gateway Earth stations, Digisat's core services
              include systems integration, equipment sales, installation,
              engineered communication systems, mobile satcom solutions,
              worldwide internet connectivity and dedicated bandwidth
              provisioning. Additionally, Digisat offers ongoing technical
              support and professional field service on a worldwide basis
              through our United States based offices.
            </p>
          </div>
          <div className={styles.ourTeam}>
            <h3>Our Experienced Team</h3>
            <div className={styles.Img}>
            <Image src="/team.jpg" objectFit="cover" layout="fill"/>
            </div>
            <p>Digisat team consists of a diverse mixture of expert engineers and technicians assembled from well known, world class satellite and wireless communications organizations. With many years of satellite, wireless and telecom experience, Digisat has the expertise to fulfill your project requirements on all levels, above and beyond your expectations. Digisat will engineer, design, deploy, install, test and service satellite communication systems and wireless network equipment anywhere in the world. From mobile and marine satcom applications, to tower and antenna maintenance as well as teleport facility upgrades, our team of Satcom professionals has you covered around the globe.</p>

<h4>Under one Roof solutions</h4>
<div className={styles.Img}>
            <Image src="/one-roof.jpg" objectFit="cover" layout="fill"/>
            </div>
<p>Digisat unique approach to providing total communication solutions has assisted top tier companies worldwide with their communication needs. Our "unique" approach to addressing client's requirements provides a wide breadth of services for total solutions from a single source. By providing a wide array of solutions, coupled with our unparalleled satellite knowledge and strict adherence to quality, the Digisat team has allowed our customers to focus on their core business goals, network expansion and more efficient business processes.</p>
          </div>
        </div>
      </div>
    </>
  );
}
