import React from 'react'
import Head from "next/head"
import styles from "../styles/Careers.module.css"
import Image from "next/legacy/image"

export default function Careers() {
  return (
    <>
        <Head>
        <title>Careers | Digisat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.careers}>
        <div className={styles.careersHead}>
            <h2>Careers</h2>
        </div>
        <div className={styles.careersContent}>
<h3>6 MONTHS INTERNSHIP PROGRAM</h3>
<div className={styles.Img}>
<Image src="/satcom-training5.jpg" objectFit='cover' layout='fill'/>
</div>
<p>We at "Digiat Skill India Pvt Ltd" provide training, Lab setup in college campus and internship program for the students from different fields such as Mechanical, Electrical, E&TC, ITI and CIVIL background on  SATCOM (Satellite Communication), how SATCOM applications work in real life, Industry visit, Practical training of SATCOM equipment and many more theories related to Satcom.</p>
<div className={styles.Img}>
<Image src="/satcom-training6.jpg" objectFit='cover' layout='fill'/>
</div>
<p>The following are the list of experiments which can be performed in the SATCOM lab which is also included in the syllabus of engineering students. It also includes basics to learn and get started in Satellite communications training.</p>
<ul>
  <li>Soldering</li>
  <li>Production</li>
  <li>Assembly</li>
  <li>
    Various Softwares<ul>
    <li>Introduction</li>
    <li>Learning</li>
    <li>Installation</li>
    <li>Testing</li>
    </ul>
  </li>
  <li>Supply Chain</li>
  <li>Marketing (Including Incentives)</li>
  <li>Router implementation on Field</li>
  <li>V-Sat<ul>
    <li>Learning</li>
    <li>Installation</li>
    <li>Tracking</li>
    <li>Locking</li>
    </ul>
    </li>
  <li>Dish TV Production</li>
  <li>Quality Cheack<ul>
    <li>Power Coating</li>
    <li>Production </li>
    <li>Dimensions</li>
    </ul></li>
</ul>
<div className={styles.Img}>
<Image src="/satcom-training7.jpg" objectFit='cover' layout='fill'/>
</div>
        </div>
      </div>
    </>
  )
}
