import React from "react";
import Head from "next/head";
import ContactComponent from "@/components/ContactComponent";
import styles from "../styles/Contact.module.css";
import { AiFillPhone, AiOutlineMail } from "react-icons/ai";
import { GiEarthAfricaEurope } from "react-icons/gi";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact | Digisat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.contact}>
        <h2>Contact</h2>
        <div className={styles.contactSection}>
          <h3>Get in Touch</h3>
          <div className={styles.office}>
            <div className={styles.section}>
              <h4>India</h4>
              <h5>Digisat Skill India Pvt Ltd (DSIPL)</h5>
              <div>3/2, IT Knowledge Park, MIDC Kharadi Pune. INDIA</div>
              <div>
                <AiFillPhone fontSize={24} />
                <a href="tel:+919822788197">+919822788197</a>
              </div>
              <div>
                <AiOutlineMail fontSize={24} />{" "}
                <a href="mailto:krish@digisat.in">krish@digisat.in</a>
              </div>
              <div>
                <GiEarthAfricaEurope fontSize={24} />{" "}
                <a href="https://digisat.in/">digisat.in</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <ContactComponent />
    </>
  );
}