import Head from 'next/head'
import MainContainer from '@/components/MainContainer'
import Services from '@/components/ServicesComponent'
import Partners from '@/components/Partners'
import Director from '@/components/Director'
import ContactComponent from '@/components/ContactComponent'

export default function Home() {
  return (
    <>
      <Head>
        <title>Digisat Skill India</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer/>
      <Services/>
      <Partners/>
      <Director/>
      <ContactComponent/>
    </>
  )
}
