import React from 'react'
import styles from "../styles/Products.module.css"
import Link from "next/link"
import Head from "next/head"

export default function Products() {
  return (
    <>
     <Head>
      <title>Products | Digisat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/products/favicon.ico" />
      </Head>
    <div className={styles.productSection}>
    <div className={styles.productsHead}>
      <h2>Our Products</h2>
    </div>
    <div className={styles.productsList}>
           <ul>
           <Link href="/products/xicom">
              <li>
              Xicom Technology <span className={styles.rightArrow}>&rarr;</span>   
              </li>
            </Link>
            <Link href="/products/anacom">
              <li>
                Anacom <span className={styles.rightArrow}>&rarr;</span>   
              </li>
            </Link>
            <Link href="/products/norsat">
              <li>
              Norsat <span className={styles.rightArrow}>&rarr;</span>   
              </li>
            </Link>
            <Link href="/products/malibu-antenna">
              <li>
              Malibu Antenna <span className={styles.rightArrow}>&rarr;</span>   
              </li>
            </Link>  
            <Link href="/products/convertors">
              <li>
              Convertors <span className={styles.rightArrow}>&rarr;</span>   
              </li>
            </Link>
            <Link href="/products/antenna-control">
              <li>
              Antenna Control System <span className={styles.rightArrow}>&rarr;</span>   
              </li>
            </Link>
            <Link href="/products/dcss">  
              <li>
              DCSS Technology <span className={styles.rightArrow}>&rarr;</span>   
              </li>
            </Link>
            <Link href="/products/atx">
              <li>
              Satellite Systems Corporation Model ATX-3000 <span className={styles.rightArrow}>&rarr;</span>   
              </li>
            </Link>
            <Link href="/products/c-com">
              <li>
              C-COM <span className={styles.rightArrow}>&rarr;</span>   
              </li>
            </Link>
            <Link href="/products/radeus">
              <li>
              Radeus Lab <span className={styles.rightArrow}>&rarr;</span>   
              </li>
            </Link>
           </ul>
    </div>
    </div>
    </>
  )
}
