import React from 'react'
import ServicesComponent from '@/components/ServicesComponent'
import Head from "next/head"

export default function Services() {
  return (
    <>
       <Head>
     <title>Services | Digisat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/products/favicon.ico" />
     </Head> 
     <ServicesComponent/>
    </>
  )
}
