import React from 'react'
import Head from "next/head"
import styles from "../styles/Training.module.css"
import Image from "next/legacy/image"

export default function Training() {
  return (
    <>
      <Head>
      <title>Training | Digisat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.training}>
        <div className={styles.trainingHead}>
        <h2>Satcom Training</h2>
        </div>
        <div className={styles.section}>
            <h3>Satcom Training</h3>
            <div className={styles.Img}>
            <Image src="/satcom-training1.jpg" objectFit='cover' layout='fill'/>
            </div>
            <p>Digisat Skill India Pvt. Ltd. was founded and established in 2000 by Mr. Krish K. Mehkarkar. Under his direction, Digisat has a versatile and experienced team of technical specialists providing system integration expertise in the development and implementation of satellite earth station and terrestrial head ends.</p>
            <div className={styles.Img}>
            <Image src="/satcom-training3.jpg" objectFit='cover' layout='fill'/>
            </div>
            <p>Our turnkey approach is to provide innovative, technologically advanced and financially competitive solutions to new installation, retrofits and upgrades. The company achieves this combination of price competitiveness and technical excellence by utilizing an international network of industry professional and suppliers.</p>
            <div className={styles.Img}>
            <Image src="/satcom-training4.jpg" objectFit='cover' layout='fill'/>
            </div>
            <p>At Digisat we Train manpower, Research new technologies, Design Products and then manufacture them according to our customers needs. Therefore Digisat provides a complete solution in the field of Satellite communication industry.</p>
        </div>
        <div className={styles.section}>
<h3>Innovative Research &amp; Development Center For Satcom Products</h3>
<div className={styles.Img}>
            <Image src="/satcom-training2.jpg" objectFit='cover' layout='fill'/>
            </div>
<ul>
    <li>Design & Development of DTH Platform.</li>
    <li>Design & Development Vsat Network.</li>
    <li>Design & Development Video Conferencing.</li>
    <li>Design and Develop of Teleports for Video Broadcasting.</li>
    <li>Ku Band Dish Antennas.</li>
    <li>Ka Band Dish Antennas.</li>
    <li>Digital Set Top Box...MPEG4 SD & HD.</li>
    <li>Multi Satellite Reception on Single Antenna.
</li>
</ul>
        </div>
      </div>
    </>
  )
}
